version: '3.8'

services:
  mongodb-example:
    image: mongo:latest
    container_name: mongodb-example
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
      MONGO_INITDB_DATABASE: admin
    networks:
      - network-example
  mongodb-express-example:
    image: mongo-express:latest
    container_name: mongodb-express-example
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: admin
      ME_CONFIG_MONGODB_SERVER: mongodb-example
    networks:
      - network-example
    # Tambahkan depends-on agar mongodb-express menunggu mongodb-example selesai dijalankan baru mongodb-express dijalankan
    depends_on:
      - mongodb-example

networks:
  network-example:
    name: network-example
    driver: bridge
