version: '3.8'

services:
  mongodb-example:
    image: mongo:latest
    container_name: mongodb-example
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: evan
      MONGO_INITDB_ROOT_PASSWORD: evan
      MONGO_INITDB_DATABASE: admin
    networks:
      - network-example

networks:
  # yang di panggil ke servicenya itu idnya bukan namenya
  network-example:
    name: network-example
    driver: bridge
